### ISSUE TITLE
Provider won't work when eztvapi torrents url is not a magnet but a torrent link

### ISSUE THREAD

**Issue by ogero** [mancuniancol/script.pulsar.eztv-mc#2]
Example: This show S07E01
Eztvapi response: http://jsonmate.com/permalink/553ff66aaa522bae3683edfb
Urls for S07E01 are "http" protocol links to torrent files instead of "magnet" protocols, and pulsar fails with:
ERRO  linkssearch      Unable to resolve .torrent file at: http://rarbg.to/download.php?........torrent

Log: http://pastebin.com/0qkca2VE

**Comment by rarbg** [comment]
@ogero 
Do you even read news ? http://torrentfreak.com/take-over-new-eztv-domain-name-150425/

**Comment by ogero** [comment]
@rarbg
Do you even read the issue reports?

Thanks for the update on eztv.it or eztv.ch domain or whatever, but it has nothing to do with this issue report.
This pulsar provider picks the torrent links (http or magnet) from eztvapi.re domain.
And even if the eztvapi.re domain is under a takeover, the LOG points out that the api is correctly serving the tv show info json.

This report is to make the author @mancuniancol aware that when eztvapi.re answers with HTTP links instead of MAGNET links, pulsar fails to play them. (Some shows episodes DO have magnet links instead of HTTP ones).

So to be failproof, this provider maybe should be getting the magnets links from parsing the show page html ie: (https://eztv.WHATEVER/shows/208/parks-and-recreation/)

**Comment by mancuniancol** [comment]
@ogero, thanks for your report.  But, I can't get the same values that you are reporting. If I check the tt1266020 in the api, I get this result http://pastebin.com/ztyJEmYh.  Only magnets, not http as you get.  I don't know why you are getting that.

**Comment by ogero** [comment]
This is very odd. 
Now i'm getting the same response as you.
And as i can see, the last update time of the first results is "Tue, 28 Apr 2015 10:17:55 GMT" and the update time of the new results is "Wed, 29 Apr 2015 00:04:51 GMT".
But the weirdest thing is that on the first response (The one with http urls), has 120 episodes, and the newer one (the one with magnet urls), has only 95 episodes.
It seems like a totally broken cache somewhere.

This issue has been troubling me for weeks, so im preparing a PR where the magnet link is generated when an http link is served. No action when magnet.
I've tested it and it works, so you can merge it if you like.

**Comment by mancuniancol** [comment]
Ok. I will check it this weekend. But, it is not necessary to convert the link.  Pulsar handles http uri.  The only thing to do is erase the infohash in the payload, in that way Pulsar will find it.  Your idea is good, but you are forgetting the time out restriction.  I won't be practical with the 4s restriction, the provider will be too slow and Pulsar won't use any results.

Any case, I will add the exception that you have reported this weekend or next week.  :)
