### ISSUE TITLE
I can't use this provider while using a vpn on my system.

### ISSUE THREAD

**Issue by kilps31** [mancuniancol/script.pulsar.eztv-mc#4]
Is there a way to set a specific port for this provider to stream on?

**Comment by mancuniancol** [comment]
Without your log. I cannot say what it is the specific problem. It could be that Pulsar times out the provider because it is too slow. Or your vpn blocks the url.  

Pulsar is which ports to stream on. The provider uses the port http and https to get the information. The rest is Pulsar.

**Comment by kilps31** [comment]
http://xbmclogs.com/ppoogfuas

I have linked my log. It starts to download very slowly and then just stops.

**Comment by mancuniancol** [comment]
I don't see any trouble with the provider. It is giving the information as intended to pulsar. If Pulsar starts to download and it stops. It is not problem of the provider.  

You need to contact Steeve, because your problem is with Pulsar, not with the provider.

**Comment by kilps31** [comment]
Thank you very much!
